version: "3.7"

services:
  bot:
    image: merlinschumacher/canteen-bot:latest
    volumes:
      - botdata:/data
    env_file: .env
    environment:
      - BOTTOKEN:$BOTTOKEN
      - MAILSERVER:$MAILSERVER
      - MAILUSER:$MAILUSER
      - MAILPASSWORD:$MAILPASSWORD
      - DATAFOLDER:$DATAFOLDER
    restart: always
    
volumes: 
  botdata:
