on: push
name: New build on push
jobs:
  package_registry:
    name: GitHub Package Registry
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      name: Checkout Repo
    - name: Log in to registry
      env:
          DOCKER_REGISTRY_URL: docker.pkg.github.com
          DOCKER_USERNAME: ${{ secrets.GITHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGISTRY_URL
    - name: Build docker image
      run: docker build -t docker.pkg.github.com/merlinschumacher/canteen-bot/canteen-bot:latest .
    - name: Push image to registy
      run: docker push docker.pkg.github.com/merlinschumacher/canteen-bot/canteen-bot:latest
