on: push
name: New build on push
jobs:
  package_registry:
    name: GitHub Package Registry
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      name: Checkout Repo
    - uses: actions/docker/login@master
      name: Log in to registry
      env:
          DOCKER_REGISTRY_URL: docker.pkg.github.com
          DOCKER_USERNAME: ${{ secrets.GITHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
    - name: Build docker image
      uses: actions/docker/cli@master
      with:
        args: build -t docker.pkg.github.com/merlinschumacher/canteen-bot/canteen-bot:lastest .
    - name: Push image to registy
      uses: actions/docker/cli@master
      with:
        args: push docker.pkg.github.com/merlinschumacher/canteen-bot/canteen-bot:lastest
